function chooseCorrectFlag(countryID){
    switch(countryID){
        case 'USD':
            return "https://www.countryflags.io/us/flat/64.png";
        case 'AED':
            return "https://www.countryflags.io/ae/flat/64.png";
        case 'ARS':
            return "https://www.countryflags.io/ar/flat/64.png";
        case 'AUD':
            return "https://www.countryflags.io/au/flat/64.png";
        case 'BGN':
            return "https://www.countryflags.io/bg/flat/64.png";
        case 'BRL':
            return "https://www.countryflags.io/br/flat/64.png";    
        case 'BSD':
            return "https://www.countryflags.io/bs/flat/64.png";     
        case 'CAD':
            return "https://www.countryflags.io/ca/flat/64.png";  
        case 'CHF':
            return "https://www.countryflags.io/ch/flat/64.png";  
        case 'CLP':
            return "https://www.countryflags.io/cl/flat/64.png";  
        case 'CNY':
            return "https://www.countryflags.io/cn/flat/64.png";  
        case 'COP':
            return "https://www.countryflags.io/co/flat/64.png";  
        case 'CZK':
            return "https://www.countryflags.io/cz/flat/64.png";  
        case 'DKK':
            return "https://www.countryflags.io/dk/flat/64.png";  
        case 'DOP':
            return "https://www.countryflags.io/do/flat/64.png";  
        case 'EGP':
            return "https://www.countryflags.io/eg/flat/64.png";  
        case 'EUR':
            return "https://www.countryflags.io/eu/flat/64.png";  
        case 'FJD':
            return "https://www.countryflags.io/fj/flat/64.png";  
        case 'GBP':
            return "https://www.countryflags.io/gb/flat/64.png";  
        case 'GTQ':
            return "https://www.countryflags.io/gt/flat/64.png";  
        case 'HKD':
            return "https://www.countryflags.io/hk/flat/64.png";
        case 'HRK':
            return "https://www.countryflags.io/hr/flat/64.png";  
        case 'HUF':
            return "https://www.countryflags.io/hu/flat/64.png";  
        case 'IDR':
            return "https://www.countryflags.io/id/flat/64.png";  
        case 'ILS':
            return "https://www.countryflags.io/il/flat/64.png"; 
        case 'INR':
            return "https://www.countryflags.io/in/flat/64.png";
        case 'ISK':
            return "https://www.countryflags.io/is/flat/64.png";
        case 'JPY':
            return "https://www.countryflags.io/jp/flat/64.png";
        case 'KRW':
            return "https://www.countryflags.io/kr/flat/64.png";
        case 'KZT':
            return "https://www.countryflags.io/kz/flat/64.png";
        case 'MVR':
            return "https://www.countryflags.io/mv/flat/64.png";
        case 'MXN':
            return "https://www.countryflags.io/mx/flat/64.png";
        case 'MYR':
            return "https://www.countryflags.io/my/flat/64.png";
        case 'NOK':
            return "https://www.countryflags.io/no/flat/64.png";
        case 'NZD':
            return "https://www.countryflags.io/nz/flat/64.png";
        case 'PAB':
            return "https://www.countryflags.io/pa/flat/64.png";
        case 'PEN':
            return "https://www.countryflags.io/pe/flat/64.png";
        case 'PHP':
            return "https://www.countryflags.io/ph/flat/64.png";
        case 'PKR':
            return "https://www.countryflags.io/pk/flat/64.png";
        case 'PLN':
            return "https://www.countryflags.io/pl/flat/64.png";
        case 'PYG':
            return "https://www.countryflags.io/py/flat/64.png";
        case 'RON':
            return "https://www.countryflags.io/ro/flat/64.png";
        case 'RUB':
            return "https://www.countryflags.io/ru/flat/64.png";
        case 'SAR':
            return "https://www.countryflags.io/sa/flat/64.png";
        case 'SEK':
            return "https://www.countryflags.io/se/flat/64.png";
        case 'SGD':
            return "https://www.countryflags.io/sg/flat/64.png";
        case 'THB':
            return "https://www.countryflags.io/th/flat/64.png";
        case 'TRY':
            return "https://www.countryflags.io/tr/flat/64.png";
        case 'TWD':
            return "https://www.countryflags.io/tw/flat/64.png";
        case 'UAH':
            return "https://www.countryflags.io/ua/flat/64.png";
        case 'UYU':
            return "https://www.countryflags.io/uy/flat/64.png";
        case 'ZAR':
            return "https://www.countryflags.io/za/flat/64.png";
        case 'btc':
            return "./crypto-logos/" + countryID + ".png";
        case 'eth':
            return "./crypto-logos/" + countryID + ".png";
        case 'xrp':
            return "./crypto-logos/" + countryID + ".png";
        case 'dot':
            return "./crypto-logos/" + countryID + ".png";
        case 'bch':
            return "./crypto-logos/" + countryID + ".png";
        case 'bnb':
            return "./crypto-logos/" + countryID + ".png";
        case 'link':
            return "./crypto-logos/" + countryID + ".png";
        case 'cro':
            return "./crypto-logos/" + countryID + ".png";
        case 'ltc':
            return "./crypto-logos/" + countryID + ".png";
    };
};

function exchangeAPICollector(API, currencyID){

    switch(currencyID){
        case 'USD':
            return API.conversion_rates.USD;
        case 'AED':
            return API.conversion_rates.AED;
        case 'ARS':
            return API.conversion_rates.ARS;
        case 'AUD':
            return API.conversion_rates.AUD;
        case 'BGN':
            return API.conversion_rates.BGN;
        case 'BRL':
            return API.conversion_rates.BRL;
        case 'BSD':
            return API.conversion_rates.BSD;
        case 'CAD':
            return API.conversion_rates.CAD;
        case 'CHF':
            return API.conversion_rates.CHF;
        case 'CLP':
            return API.conversion_rates.CLP;
        case 'CNY':
            return API.conversion_rates.CNY;
        case 'COP':
            return API.conversion_rates.COP;
        case 'CZK':
            return API.conversion_rates.CZK;
        case 'DKK':
            return API.conversion_rates.DKK;
        case 'DOP':
            return API.conversion_rates.DOP;
        case 'EGP':
            return API.conversion_rates.EGP;
        case 'EUR':
            return API.conversion_rates.EUR;
        case 'FJD':
            return API.conversion_rates.FJD;
        case 'GBP':
            return API.conversion_rates.GBP;
        case 'GTQ':
            return API.conversion_rates.GTQ;
        case 'HKD':
            return API.conversion_rates.HKD;
        case 'HRK':
            return API.conversion_rates.HRK;
        case 'HUF':
            return API.conversion_rates.HUF;
        case 'IDR':
            return API.conversion_rates.IDR;
        case 'ILS':
            return API.conversion_rates.ILS;
        case 'INR':
            return API.conversion_rates.INR;
        case 'ISK':
            return API.conversion_rates.ISK;
        case 'JPY':
            return API.conversion_rates.JPY;
        case 'KRW':
            return API.conversion_rates.KRW;
        case 'KZT':
            return API.conversion_rates.KZT;
        case 'MVR':
            return API.conversion_rates.MVR;
        case 'MXN':
            return API.conversion_rates.MXN;
        case 'MYR':
            return API.conversion_rates.MYR;
        case 'NOK':
            return API.conversion_rates.NOK;
        case 'NZD':
            return API.conversion_rates.NZD;
        case 'PAB':
            return API.conversion_rates.PAB;
        case 'PEN':
            return API.conversion_rates.PEN;
        case 'PHP':
            return API.conversion_rates.PHP;
        case 'PKR':
            return API.conversion_rates.PKR;
        case 'PLN':
            return API.conversion_rates.PLN;
        case 'PYG':
            return API.conversion_rates.PYG;
        case 'RON':
            return API.conversion_rates.RON;
        case 'RUB':
            return API.conversion_rates.RUB;
        case 'SAR':
            return API.conversion_rates.SAR;
        case 'SEK':
            return API.conversion_rates.SEK;
        case 'SGD':
            return API.conversion_rates.SGD;
        case 'THB':
            return API.conversion_rates.THB;
        case 'TRY':
            return API.conversion_rates.TRY;
        case 'TWD':
            return API.conversion_rates.TWD;
        case 'UAH':
            return API.conversion_rates.UAH;
        case 'UYU':
            return API.conversion_rates.UYU;
        case 'ZAR':
            return API.conversion_rates.ZAR;
    };
};

function getCryptoFullName(ID){
    switch(ID){
        case "btc":
            return "bitcoin"
        case "eth":
            return "ethereum"
        case "xrp":
            return "ripple"
        case "btc":
            return "Bitcoin"
        case "dot":
            return "polkadot"
        case "bch":
            return "bitcoin-cash"
        case "bnb":
            return "binancecoin"
        case "link":
            return "chainlink"
        case "cro":
            return "crypto-com-chain"
        case "ltc":
            return "litecoin"
    }
}

function exchangeCryptoAPICollector(API, currencyID, convertID){
    var cryptoCurrencyFullName = getCryptoFullName(convertID);
    var cryptoExchage = API[cryptoCurrencyFullName][currencyID.toLowerCase()];
    return cryptoExchage;
}

function chooseCurrencySymbol(countryID) {
    switch (countryID) {
        case 'USD': 
            return "&#36;";
        case 'AED':
            return "&#1583;.&#1573;";
        case 'ARS':
            return "&#36;";
        case 'AUD':
            return "&#36;";
        case 'BGN':
            return "&#1083;&#1074;";
        case 'BRL':
            return "&#82;&#36;";
        case 'BSD':
            return "&#36;";
        case 'CAD':
            return "&#36;";
        case 'CHF':
            return "&#67;&#72;&#70;";
        case 'CLP':
            return "&#36;";
        case 'CNY':
            return "&#165;";
        case 'COP':
            return "&#36;";
        case 'CZK':
            return "&#75;&#269;";
        case 'DKK':
            return "&#107;&#114;";
        case 'DOP':
            return "&#82;&#68;&#36;";
        case 'EGP':
            return "&#163;";
        case 'EUR':
            return "€";
        case 'FJD':
            return "&#36;";
        case 'GBP':
            return "&#163;";
        case 'GTQ':
            return "&#81;";
        case 'HKD':
            return "&#36;";
        case 'HRK':
            return "&#107;&#110;";
        case 'HUF':
            return "&#70;&#116;";
        case 'IDR':
            return "&#82;&#112;";
        case 'ILS':
            return "&#8362;";
        case 'INR':
            return "&#8377;";
        case 'ISK':
            return "&#107;&#114;";
        case 'JPY':
            return "&#165;";
        case 'KRW':
            return "&#8361;";
        case 'KZT':
            return "&#1083;&#1074;"
        case 'MVR':
            return "ރ";
        case 'MXN':
            return "&#36;";
        case 'MYR':
            return "&#82;&#77;";
        case 'NOK':
            return "&#107;&#114;";
        case 'NZD':
            return "&#36;";
        case 'PAB':
            return "&#66;&#47;&#46;";
        case 'PEN':
            return "&#83;&#47;&#46;";
        case 'PHP':
            return "&#8369;";
        case 'PKR':
            return "&#8360;";
        case 'PLN':
            return "&#122;&#322;";
        case 'PYG':
            return "&#71;&#115;";
        case 'RON':
            return "&#108;&#101;&#105;";
        case 'RUB':
            return "&#1088;&#1091;&#1073;";
        case 'SAR':
            return "&#65020;";
        case 'SEK':
            return "&#107;&#114;";
        case 'SGD':
            return "&#36;";
        case 'THB':
            return "&#3647;";
        case 'TRY':
            return "&#;";
        case 'TWD':
            return "&#78;&#84;&#36;";
        case 'UAH':
            return "&#8372;";
        case 'UYU':
            return "&#36;&#85;";
        case 'ZAR':
            return "&#82;";
        default:
            return "";
    };
};